### ISSUE TITLE
Subset columns to MIxS terms (version 5)

### ISSUE THREAD

**Issue by wdduncan** [INCATools/biosample-analysis#19]
Create a version of biosample data whose columns are MIxS 5 terms. Not all the harmonized names (e.g., 'fire') MIxS terms.

cc @cmungall @realmarcin

**Comment by cmungall** [comment]
fire is in mixs

**Comment by cmungall** [comment]
I suggest before starting this, catalog the list of fields not in mixs, we may need to make a sssom mapping

**Comment by wdduncan** [comment]
I going to subset using the non-human environmental package terms.
- air
- soil
-sediment
- water

**Comment by wdduncan** [comment]
See notebook `build-non-human-samples.ipynb`:
https://github.com/INCATools/biosample-analysis/blob/master/src/notebooks/build-non-human-samples.ipynb 

This notebook is subset to env_packages containing the strings:
- 'air'
- 'soil'
- 'sediment' 
- 'plant-associated'
- 'water'

Output has been saved to `target/non-human-samples.tsv.gz`.  

Potential enhancements to `target/non-human-samples.tsv.gz`:
- include packages containing 'plant' instead of 'plant-associated'.
- normalize all package names as described in #24 
- replace values indicating missing data with NaNs

cc @realmarcin
