### ISSUE TITLE
Perform NER on sample metadata

### ISSUE THREAD

**Issue by wdduncan** [INCATools/biosample-analysis#28]
Test NER on a large set of samples using text fields.    
Fields to consider:
- title
- paragraph
- taxonomy_name
- env_package
- ... add more in responses

Tools to use: OGER, SciGraph Annotator, others?
Need to test for plurals (e.g. deserts => desert).

cc @cmungall

**Comment by cmungall** [comment]
we need to do a join with study metadata to get more text

**Comment by wdduncan** [comment]
Here a small dataset to test with.

[water-soil-plant-test.csv.gz](https://github.com/INCATools/biosample-analysis/files/5308726/water-soil-plant-test.csv.gz)
