### ISSUE TITLE
create NMDC biosample file for OGER/runNER

### ISSUE THREAD

**Issue by wdduncan** [INCATools/biosample-analysis#44]
In order to do NER on the NMDC biosample table, create a slimmed down biosample table of fields used to determine GOLD paths.

cc @hrshdhgd

**Comment by wdduncan** [comment]
@hrshdhgd I've created a table in `downloads/nmdc-biosample-table-for-ner-20201016.tsv` that has the fields used to determine the mixs triad in the NMDC biosample table.

A document describing how the mixs triad is determine is found [here](https://docs.google.com/document/d/1_WkxKCw_Msb_4z2d0QkdnmyKyGtlSRlta8GeBSfCjVU/edit) if you are interested.

**Comment by hrshdhgd** [comment]
I have create many output files locate [here](https://drive.google.com/drive/folders/1aBcXh0uGKKNHtySrK2qY462WrGztOK7N?usp=sharing). The ones we had discussed are :

1. [The runNER output](https://docs.google.com/uc?export=download&id=1aSKhEbLd-39P4ll1k_zWCtwmg4kTwfQg)
2. [The combined output with original input text.](https://docs.google.com/uc?export=download&id=1EFigGRUScky_xCZ0svc2ZKp3gRzb5iB9)

**Comment by wdduncan** [comment]
Done. See PR https://github.com/INCATools/biosample-analysis/pull/46
