### ISSUE TITLE
target/occurrences-%.tsv make recipe can't find tabs

### ISSUE THREAD

**Issue by turbomam** [INCATools/biosample-analysis#49]
This recipe searches for tab delimiters with this **general** pattern

```bash
egrep $'\t' target/attributes.tsv
```
@cmungall I guess that must work on your Mac, but it doesn't work in Ubuntu

Alternatives include 

```bash
egrep $'\t' target/attributes.tsv
```
 and

```bash
grep -P '\t' target/attributes.tsv
```

@wdduncan This is what we were just discussing this morning

**Comment by turbomam** [comment]
actually, I couldn't get the recipe to work with

```make
egrep $'^$*\t' $< | cut -f2 > $@
```

or

```make
egrep $$'^$*\t' $< | cut -f2 > $@
```

so I'd like to propose


```make
grep -P '^$*\t' $< | cut -f2 > $@
```

unless we want to use one of those approaches that changes the recipe based on the OS.

**Comment by cmungall** [comment]
I don't care so much so long as there is not an order of magnitude difference in speed. This whole hacky grep method is less necessary now we can do a sql query
