### ISSUE TITLE
Only collect harmonized_name when building sample TSV

### ISSUE THREAD

**Issue by cmungall** [INCATools/biosample-analysis#6]
We only care about harmonized_name (ie mixs) for now. We can do an analysis of others later.

This should substantially reduce the time to build the table, as well as the resulting size

**Comment by wdduncan** [comment]
I created an EAV using this script: https://github.com/INCATools/biosample-analysis/blob/master/util/harmonized-name-eav.pl

There are 447 harmonized attributes. See notebook https://nbviewer.jupyter.org/github/INCATools/biosample-analysis/blob/master/src/notebooks/analyze-harmonized-data.ipynb

**Comment by cmungall** [comment]
Where is the tsv deposited?

**Comment by wdduncan** [comment]
I haven't uploaded it yet. But I will :)

**Comment by wdduncan** [comment]
Details of where the harmonized data exist is on the main README.
cc @cmungall
