### ISSUE TITLE
Where did these folders come from?

### ISSUE THREAD

**Issue by turbomam** [INCATools/biosample-analysis#60]
@wdduncan @cmungall 

I have `gensc.github.io/` in the root directory/master branch of `INCATools/biosample-analysis`. I think it had to do with some integration we were doing with `mixs.yaml`.

Same thing with `queries/Script-1.sql`.  It looks like a pure SQL implementation of what I had done in in a notebook in the gold ontology repo. https://github.com/cmungall/gold-ontology/blob/main/notebooks/goldpaths_to_triads_by_proportion.ipynb

If they're considered "Untracked", could they have gotten into my file system from some other route than me creating them locally? Should I push them?

```
biosample-analysis % git status 
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   Makefile
	modified:   target/emp_studies.tsv
	modified:   util/save-harmonized-table-to-sqlite.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	gensc.github.io/
	queries/
```

**Comment by wdduncan** [comment]
I have not idea what these files are. They don't appear locally on my computer either.
