### ISSUE TITLE
Additional fields to include

### ISSUE THREAD

**Issue by cmungall** [INCATools/biosample-analysis#7]
We need text additional fields for text mining experiments

e.g.

```
  <Description>
    <Title>Alistipes putredinis DSM 17216</Title>
    <Organism taxonomy_id="445970" taxonomy_name="Alistipes putredinis DSM 17216"/>
    <Comment>
      <Paragraph>Alistipes putredinis (GenBank Accession Number for 16S rDNA gene: L16497) is a member of the Bacteroidetes division of the domain bacteria and has been isolated from human feces. It has been found in 16S rDNA sequence-based enumerations of the colonic microbiota of adult humans (Eckburg et. al. (2005), Ley et. al. (2006)). </Paragraph>
      <Paragraph>Keywords: GSC:MIxS;MIGS:5.0</Paragraph>
    </Comment>
  </Description>
```

Add additional columns

 - title
 - organism_taxonomy_id
 - comment (concatenation of paragraphs)

Also we want to capture all external IDs

e.g.

```
    <Id db="SRA">SRS058998</Id>
    <Id db="BioSample" is_primary="1">SAMN00011046</Id>
    <Id db="GEO" db_label="Sample name">GSM531786</Id>
    <Id db="SRA">SRS058999</Id>
    <Id db="BioSample" is_primary="1">SAMN00011047</Id>
    <Id db="GEO" db_label="Sample name">GSM531787</Id>
    <Id db="SRA">SRS059000</Id>
    <Id db="BioSample" is_primary="1">SAMN00011048</Id>
```

I suggest either

 - one column, xrefs, with a value of a `|` concatenated set of CURIEs (e.g. SRA:SRS059000)
 - OR one column per prefix, single-valued

**Comment by wdduncan** [comment]
Ok. I can make a lookup table. AFIK, all samples have a biosample and sra IDs. I'll do a scan for any other IDs not mentioned above.

**Comment by wdduncan** [comment]
Added the following fields to data:
- title
- paragraph
- taxonomy
- taxonomy_name
- db_id: in the form of <dabase>:<id> (e.g., SRA:SRS058999)
- model (e.g, <Model>MIGS.ba</Model>)
- package
- package display name (e.g., <Package display_name="Generic">Generic.1.0</Package>)
- status, status_date (e.g., <Status status="live" when="2013-08-05T10:18:49"/>)
- dna_source (e.g., <Link type="url" label="DNA Source">http://www.dsmz.de/catalogues/details/culture/DSM-1402</Link>) 
- entrez_target, entrez_label, entrez_value (e.g.,  <Link type="entrez" target="bioproject" label="PRJNA12851">12851</Link>)

Data can be downloaded  from:
https://drive.google.com/drive/u/1/folders/1eL0v0stoduahjDpoDJIk3z2pJBAU4b2Y
